version: "3.8"

services:
  backend:
    image: pramithamj/pft_backend:v1.0.0
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/pft-mern
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8000
    depends_on:
      - mongodb
    env_file:
      - .env

  frontend:
    image: pramithamj/pft_frontend:v1.0.0
    ports:
      - "3000:3000"
    environment:
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_PASSWORD=${FIREBASE_PASSWORD}
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
