export const dashboard = <i className="fa-solid fa-chart-line fa-beat-fade"></i>
export const transactions = <i className="fa-solid fa-credit-card fa-beat-fade"></i>
export const categories = <i className="fa-solid fa-tags fa-bounce"></i>
export const accounts = <i className="fa-solid fa-wallet fa-bounce"></i>
export const settings = <i className="fa-solid fa-cog fa-bounce"></i>
export const logout = <i className="fa-solid fa-sign-out fa-bounce"></i>
export const trend = <i className="fa-solid fa-money-bill-trend-up fa-beat-fade"></i>
export const expenses = <i className="fa-solid fa-money-bill-transfer fa-beat-fade"></i>
export const money = <i className="fa-solid fa-money-bill fa-bounce"></i>
export const freelance = <i className ="fa-solid fa-earth-americas fa-bounce"></i>
export const stocks = <i className="fa-solid fa-arrow-trend-up fa-bounce"></i>
export const bitcoin = <i className="fa-brands fa-bitcoin fa-bounce"></i>
export const piggy = <i className="fa-solid fa-piggy-bank fa-bounce"></i>
export const yt = <i className="fa-brands fa-youtube fa-bounce"></i>
export const card = <i className="fa-brands fa-cc-visa fa-bounce"></i>
export const users = <i className="fa-solid fa-users-between-lines fa-bounce"></i>
export const dollar = <i className="fa-solid fa-dollar-sign fa-bounce"></i>
export const calender = <i className="fa-solid fa-calendar "></i>
export const comment = <i className="fa-solid fa-comment "></i>
export const plus = <i className="fa-solid fa-plus fa-bounce"></i>
export const trash = <i className="fa-solid fa-trash "></i>
export const signout = <i className="fa-solid fa-right-from-bracket fa-beat-fade"></i>
export const takeaway = <i className="fa-solid fa-utensils fa-bounce"></i>
export const clothing = <i className="fa-solid fa-shirt fa-bounce"></i>
export const book = <i className="fa-solid fa-book-open fa-bounce"></i>
export const medical = <i className="fa-solid fa-briefcase-medical fa-bounce"></i>
export const tv = <i className="fa-solid fa-tv fa-bounce"></i>
export const circle = <i className="fa-solid fa-circle-dot fa-bounce"></i>
export const edit = <i className="fa-solid fa-pen-to-square "></i>
export const save = <i className="fa-solid fa-floppy-disk fa-bounce"></i>
export const cancel = <i className="fa-solid fa-x "></i>
export const search = <i className="fa-solid fa-search fa-bounce"></i>
export const gift = <i className="fa-solid fa-gift fa-bounce"></i>
export const bank = <i className="fa-solid fa-bank fa-bounce"></i>
export const home = <i className="fa-solid fa-home fa-bounce"></i>
export const travelling = <i className="fa-solid fa-plane fa-bounce"></i>
export const other = <i className="fa-solid fa-ellipsis-h fa-bounce"></i>
export const pocketMoney = <i className="fa-brands fa-get-pocket fa-bounce"></i>
export const salary = <i className="fa-solid fa-money-bill-wave fa-bounce"></i>
export const commition = <i className="fa-solid fa-money-check-dollar fa-bounce"></i>
export const investments = <i className="fa-solid fa-chart-line fa-bounce"></i>
export const interest = <i className="fa-solid fa-money-bill-wave fa-bounce"></i>
export const history = <i className="fa-solid fa-clock-rotate-left fa-beat-fade"></i>
export const help = <i className="fa-solid fa-question-circle fa-beat-fade"></i>
export const about = <i className="fa-solid fa-info-circle fa-bounce"></i>
export const github = <i className="fa-brands fa-github fa-bounce"></i>
export const google = <i className="fa-brands fa-google fa-beat-fade"></i>
export const linkedin = <i className="fa-brands fa-linkedin fa-beat-fade"></i>
export const twitter = <i className="fa-brands fa-twitter fa-beat-fade"></i>
export const facebook = <i className="fa-brands fa-facebook fa-beat-fade"></i>
export const instagram = <i className="fa-brands fa-instagram fa-bounce"></i>
export const youtube = <i className="fa-brands fa-youtube fa-beat-fade"></i>
export const email2 = <i className="fa-solid fa-envelope fa-beat-fade"></i>
export const password2 = <i className="fa-solid fa-key fa-beat-fade"></i>
export const username = <i className="fa-solid fa-user fa-bounce"></i>
export const loginIcon = <i className="fa-solid fa-right-to-bracket fa-beat-fade"></i>
export const signup = <i className="fa-solid fa-user-plus fa-beat-fade"></i>
export const signup2 = <i className="fa-solid fa-user-plus fa-beat-fade"></i>
export const forgot = <i className="fa-solid fa-question-circle fa-bounce"></i>
export const rent = <i className="fa-solid fa-house fa-bounce"></i>
export const taxi = <i className="fa-solid fa-taxi fa-bounce"></i>
export const food = <i className="fa-solid fa-bowl-food fa-bounce"></i>
export const add = <i className="fa-solid fa-plus fa-bounce"></i>

